---
- name: Install and Start Nginx
  hosts: web_servers
  become: yes

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
