---
- name: Install and Start Nginx
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
