---
- name: Install Nginx & Deploy
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    vars:
        ansible_become_pass: /home/ubuntu/keys/jenkins_ansible.pem
