---
- name: Install Nginx & Deploy
  hosts: localhost
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/keys/jenkins_anisble.pem


  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

