---
- name: Install and Start Nginx
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
  vars:
  ansible_ssh_private_key_file: /home/ubuntu/keys/jenkins_ansible.pem
